TODO: Seanpm2001-Snapcraft
File: /.todo.yml
Tasks: [
  Maintenance: [
    Metadata: "Add metadata" [
      Tags: "Add tags"
      Link: "Add URL"
      Other: "Add other metadata"
    ];
    README: "Update README.md file" [
      Changes: [
        Icon: "Add icon"
        Desc: "Improve description"
        List: "List Snapcraft projects with links"
        Other: "Other/Unspecified"
      ];
      Other: "Other/Unspecified"
    ];
  ];
  Updates: [
    UpdateDesc: "Update snapcraft projects"
    Requirement: "Finish maintenance steps, and publish a release first"
  ];
];
# File info
# File type: YAML source file (*.yml)
# File version: 1 (2022, Friday, August 12th at 8:21 pm PST)
# Line count (including blank lines and compiler line): 29
